version: '3'
services:
  backend:
    build:
      context: ./back_project
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - mean-network

  frontend:
    build:
      context: ./project_front
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - mean-network

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - mean-network

networks:
  mean-network:
    driver: bridge

volumes:
  mongo-data: